### ISSUE TITLE
How to unbind affix after resizing window to certain width

### ISSUE THREAD

**Issue by tejashapani** [jasonalvis/affix#2]
Hello,

Is there any option to unbind affix when resizing window to certain width?
Because when resizing window to tab view, then i would like to unbind affix and want to scroll as normal.

I tried with jQuery("#container").affix("checkPosition"); but it does not work.

Any help on this would be appreciate.

Thanks
Tejas

**Comment by jasonujmaalvis** [comment]
There is no built in method to destroy the affix at present but you could add your own to affix JS file:

```
Affix.prototype.destroy = function() {
    // Remove scroll event
    this.$target.off('scroll.affix');

    // Remove inline styles
    this.$element.removeAttr('style');
};
```

You'll also need to amend this [line](https://github.com/jasonalvis/affix/blob/master/demo/js/affix.js#L72) to read like so:

`this.$target.on('scroll.affix', $.proxy(this.checkPosition, this));`

Finally call the method whenever you want to destroy it:

`$('#container').affix('destroy');`
